### ISSUE TITLE
how to write example.c

### ISSUE THREAD

**Issue by wubo0067** [YutaroHayakawa/ipftrace2#15]
an example in readme.md: ### sudo ipft -m 0xdeadbeef -e example.c

How should I write example.c, I don't see the code in the project?

**Comment by YutaroHayakawa** [comment]
Thanks for your report, but we do have a code here.

https://github.com/YutaroHayakawa/ipftrace2/blob/master/example/extensions/bpf/gso/gso.bpf.c

Also, you can see this instruction

https://github.com/YutaroHayakawa/ipftrace2/blob/master/docs/bpf_extension.md
