### ISSUE TITLE
Issue running "ipft -m 0xdeadbeef"

### ISSUE THREAD

**Issue by Agyapal** [YutaroHayakawa/ipftrace2#4]
I was able to install it successfully. But when I ran: ipft -m 0xdeadbeef, I go this error:

ipft -m 0xdeadbeef
Couldn't find type die of sk_buff
debuginfo_offsetof failed
load_progs failed
Trace failed with error

uname -a
Linux ip-172-31-38-178 4.14.171-105.231.amzn1.x86_64 #1 SMP Thu Feb 27 23:49:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

After I installed kernel-debuginfo error is gone but now I landed up in this error:

ipft -m 0xdeadbeef -r "ip_.*"
fopen: No such file or directory
read_available_filter_functions failed
traceable_set_create failed
attach_progs failed
Trace failed with error

Am I missing some syntax here. Any suggestions?

**Comment by YutaroHayakawa** [comment]
Perhaps it is failing to open the `/sys/kernel/debug/tracing/available_filter_functions`. Maybe you need to mount the debugfs. Could you do `mount -t debugfs none /sys/kernel/debug` and try again?

https://github.com/YutaroHayakawa/ipftrace2/blob/21b3515147774f0ef4d98272850521bb83b6d9ea/src/traceable_set.c#L53

**Comment by Agyapal** [comment]
After I mounted as you suggested, I got few errors and it finally says Trace ready!

ipft -m 0xdeadbeef
Attaching program (total 1447, succeeded 0, failed 0 filtered: 0 untraceable: 1)Failed to open /sys/bus/event_source/devices/kprobe/type: No such file or directory
Failed to get perf type
Attaching program (total 1447, succeeded 0, failed 1 filtered: 0 untraceable: 4)Failed to open /sys/bus/event_source/devices/kprobe/type: No such file or directory
Failed to get perf type
................
................
Attaching program (total 1447, succeeded 0, failed 771 filtered: 0 untraceable: 674)Failed to open /sys/bus/event_source/devices/kprobe/type: No such file or directory
Failed to get perf type
Attaching program (total 1447, succeeded 0, failed 772 filtered: 0 untraceable: 675)
Trace ready!

Are these errors expected?

Also I see Trace ready message which means we are all set to trace but when I ping 1.1.1.1 as stated in this document, I do not see any traces coming up.

**Comment by YutaroHayakawa** [comment]
It's unexpected. As you see, attach of the eBPF program to kprobe event is all failing. That's why you don't get anything.

Does /sys/bus/event_source/devices/kprobe/type existing in your running environment? What do you see under /sys/bus/event_source?

**Comment by Agyapal** [comment]
> /sys/bus/event_source 

I do not see kprobe/type under  /sys/bus/event_source/devices

[root@ip-172-31-38-178 ~]# ls /sys/bus/event_source
devices  drivers  drivers_autoprobe  drivers_probe  uevent
[root@ip-172-31-38-178 ~]# ls /sys/bus/event_source/devices/
breakpoint  msr  software  tracepoint
[root@ip-172-31-38-178 ~]#

**Comment by YutaroHayakawa** [comment]
Oh, I just noticed that the kprobe based perf event we use in ipftrace2 is only supported from kernel 4.17.

https://github.com/torvalds/linux/commit/65074d43fc77bcae32776724b7fa2696923c78e4

So the minimal supported version in our README is actually wrong. I'll fix that.

If you can upgrade your kernel, could upgrade it to >= 4.17 and try again?

**Comment by Agyapal** [comment]
I am using AWS Amazon Linux and looks like the latest version we have is 4.14

uname -a
Linux ip-172-31-38-178 4.14.171-105.231.amzn1.x86_64 #1 SMP Thu Feb 27 23:49:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Will test it on some other distro and revert

**Comment by YutaroHayakawa** [comment]
Let me close this issue for now. Please reopen this if you have farther questions :)
