### ISSUE TITLE
%return

### ISSUE THREAD

**Issue by splitice** [YutaroHayakawa/ipftrace2#6]
Would it also be possible to attach the program to %return on the functions? That way an easy benchmark could be acheived.

**Comment by YutaroHayakawa** [comment]
Currently, it's impossible, but it will be supported in the future.

Detail:

ipftrace2 depends on the `skb->mark` field to make sure which packet to trace, means if we want to support it, we need to be able to access to the function argument in the context of return hook. However, our current tracing backend (kprobe/kretprobe) doesn't allow us to access to the function argument in return hook.

Recent kernel (>=5.5) provides new type of tracing backend (fentry/fexit) which allows us to access to the function argument in the context of return hook. Once ipftrace2 supports it, we should be able to measure the time the function call took.

**Comment by YutaroHayakawa** [comment]
Now function return tracing has been supported since v0.5.0.

https://github.com/YutaroHayakawa/ipftrace2/releases/tag/v0.5.0
