### ISSUE TITLE
Some functions cannot be traced

### ISSUE THREAD

**Issue by ShouheiNishi** [YutaroHayakawa/ipftrace2#9]
The gtp5g, the GTP-U driver, was traced with ipftrace2 by the following procedure, 

https://www.apresiatac.jp/blog/202204136589/　(In Japanese) 

Some functions, such as udp_tunnel_xmit_skb, were lacked in the trace. The following check code in the src/symsdb .c seem to be the cause.
    /*
     * Function takes more than MAX_SKB_POS shouldn't be traced
     */
    if (btf_vlen(func_proto) > MAX_SKB_POS) {
      continue;
    }
When this code is commented out, this issue seems to be resolved.

**Comment by YutaroHayakawa** [comment]
Hi, thank you for your report!

The checking you pointed out looks unnecessary for me as well. However, seems removing it breaks the `function_graph` tracer. I'll investigate the cause.
